const objectFiles = ["Advanced_Lifter",
    "Class_1_Drive",
    "Class_2_Drone",
    "Defense_Prototype",
    "Fusion_Hulk",
    "Heavy_Driller",
    "Heavy_Hulk",
    "Level_27_Boss",
    "Level_7_Boss",
    "Light_Hulk",
    "Medium_Hulk",
    "Medium_Lifter",
    "Pyro_GX",
    "Spider_Processing_Robot",
    "Vulcan_Driller"];